---
- name: artifactory | Install dependencies
  apt: pkg={{ item }} state=installed
  with_items:
    - unzip
    - net-tools
    - openjdk-8*
  tags: artifactory

- name: artifactory | Download artifactory zip
  get_url: url={{ artifactory_zip_url }} dest=/opt/{{ artifactory_zip_file }}

- name: artifactory | Extract artifactory
  shell: unzip /opt/{{ artifactory_zip_file }} -d /opt  creates={{ artifactory_dir }}


- name: artifactory | Getting in to installation directory
  shell: cd /opt/artifactory-oss-6.3.3/bin

- name: artifactory| Install service
  shell: bash /opt/artifactory-oss-6.3.3/bin/installService.sh

- name: artifactory | Start/Restart artifactory
  service: name=artifactory state=started
