---
# vars file for ansible-role-docker-ce
docker_systemd_service_config_tweaks: []
docker_service_envs: {}

docker_repository_related_packages:
  CentOS:
    - yum-utils
  RedHat:
    - yum-utils
  Ubuntu:
    - apt-transport-https
    - ca-certificates
    - curl
    - software-properties-common
  Debian:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg2
    - software-properties-common

docker_repository_url:
  CentOS: https://download.docker.com/linux/centos/docker-ce.repo
  RedHat: https://download.docker.com/linux/centos/docker-ce.repo
  Fedora: https://download.docker.com/linux/fedora/docker-ce.repo

docker_cmd_check_edge_repo_status:
  CentOS: yum-config-manager docker-ce-edge | grep enabled
  RedHat: yum-config-manager docker-ce-edge | grep enabled
  Fedora: dnf config-manager --dump docker-ce-edge | grep enabled
  Ubuntu: cat /etc/apt/sources.list.d/docker-ce.list | grep edge

docker_cmd_enable_disable_edge_repo:
  CentOS: yum-config-manager --{{ (docker_enable_ce_edge == true) | ternary('enable','disable') }} docker-ce-edge
  RedHat: yum-config-manager --{{ (docker_enable_ce_edge == true) | ternary('enable','disable') }} docker-ce-edge
  Fedora: dnf config-manager --set-{{ (docker_enable_ce_edge == true) | ternary('enabled','disabled') }} docker-ce-edge

docker_cmd_update_repo_cache:
  CentOS: yum makecache fast
  RedHat: yum makecache fast
  Fedora: dnf makecache fast
  Ubuntu: apt-get update
  Debian: apt-get update

docker_envs_dir:
  CentOS: /etc/sysconfig
  RedHat: /etc/sysconfig
  Fedora: /etc/sysconfig
  Ubuntu: /etc/default
  Debian: /etc/default

docker_old_packages:
  CentOS:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine
  RedHat:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine
  Fedora:
    - docker
    - docker-common
    - container-selinux
    - docker-selinux
    - docker-engine
  Ubuntu:
    - docker
    - docker-engine
    - docker.io
  Debian:
    - docker
    - docker-engine
    - docker.io
# Daemon configuration (https://docs.docker.com/engine/reference/commandline/dockerd/)
# Example:
# docker_daemon_config:
#   experimental: true
docker_daemon_config: {}
# Docker daemon options
#  Docker daemon is configured with '-H fd://' by default in Ubuntu/Debian which cause problems.
#  https://github.com/moby/moby/issues/25471
docker_daemon_opts: ''
# Map of environment variables to Docker daemon
docker_daemon_envs: {}
# List of additional service configuration options for systemd
# Important! Configuring this can cause Docker to not start at all.
docker_systemd_service_config: []
# To compensate for situation where Docker daemon fails because of usermod incompatibility.
# Ensures that 'dockremap:500000:65536' is present in /etc/subuid and /etc/subgid.
# Note! If userns-remap is set to 'default' in docker_daemon_config this config will be unnecessary.
docker_bug_usermod: false
# Enable auditing of Docker related files and directories
docker_enable_audit: false
# Enable Docker CE Edge
docker_enable_ce_edge: false
# Set `MountFlags=slave`
#  https://github.com/haxorof/ansible-role-docker-ce/issues/34
docker_enable_mount_flag_fix: yes
# Always ensure latest version of Docker CE
docker_latest_version: true
# Docker package to install. Change this if you want a specific version of Docker
docker_pkg_name: docker-ce
# If below variable is set to true it will remove older Docker installation before Docker CE.
docker_remove_pre_ce: false