---
# tasks file for apache

- name: Installing httpd (Apache)
  apt:
    name: apache2
    state: latest

- name: enable module proxy on apache
  command: a2enmod proxy proxy_http

- name: start service httpd - if install succeeded
  service:
    name: apache2
    state: started

- name: ajout du template
  template:
    src: artifactory.conf.j2
    dest: /etc/apache2/sites-available/artifactory.conf

- name: activation du template artifactory et redémarrage du service
  command: a2ensite artifactory.conf

- name: reload le service apache
  command: service apache2 reload
  become: true
...
