---
# tasks file for apache

- name: Installing httpd (Apache)
  apt:
    name: apache2
    state: latest

- name: enable modules
  apache2_module:
    state: present
    name: "{{ item }}"
  with_items:
  - proxy
  - proxy_http


- name: start service httpd - if install succeeded
  service:
    name: apache2
    state: started

- name: ajout du template default
  template:
    src: 000-default.conf.j2
    dest: /etc/apache2/sites-available/000-default.conf
  notify:
    - restart apache
...
