---
# Install and configure GitLab Community Edition
- include_tasks: gitlab-ce.yml

# Create a Website in Nginx if it is installed
- name: Check if Nginx is installed
  stat:
    path: /etc/nginx
  register: nginx

- include_tasks: nginx.yml
  when: nginx.stat.exists
