# Configuration to avoid 'Device or resource busy'
- block:
  - name: Stat /proc/sys/fs/may_detach_mounts (CentOS/RedHat)
    stat:
      path: /proc/sys/fs/may_detach_mounts
    register: may_detach_mounts

  - name: Ensure fs.may_detach_mounts is set to avoid 'Device or resource busy' (CentOS/RedHat)
    sysctl:
      name: fs.may_detach_mounts
      value: 1
      sysctl_file: /etc/sysctl.d/99-docker.conf
      reload: yes
    become: yes
    when: may_detach_mounts.stat.exists

  # Keep for compatibility reasons of this role. Now everything is in the same file.
  - name: Remove systemd drop-in for Docker Mount Flags slave configuration (CentOS/RedHat)
    file:
      path: /etc/systemd/system/docker.service.d/mountflags-slave.conf
      state: absent
    become: yes
    notify: restart docker

  - name: Set systemd service MountFlags option to "slave" to prevent "device busy" errors on CentOS/RedHat 7.3 kernels (CentOS/RedHat)
    set_fact:
      docker_systemd_service_config_tweaks: "{{ docker_systemd_service_config_tweaks + _systemd_service_config_tweaks }}"
    vars:
      _systemd_service_config_tweaks:
        - 'MountFlags=slave'
  when:
    - _docker_os_dist == "CentOS" or _docker_os_dist == "RedHat"
    - docker_enable_mount_flag_fix | bool
    - ansible_kernel | version_compare('4', '<')
