---
- name: Set docker-ce package state to latest
  set_fact:
    docker_pkg_state: 'latest'
  when: docker_latest_version|bool

- name: Ensure docker-ce is installed
  package:
    name: "{{ docker_pkg_name }}"
    state: "{{ docker_pkg_state|default('present') }}"
  become: true
  notify: restart docker
