---
# tasks file for docker
- name: Add Docker GPG key
  apt_key: url=https://download.docker.com/linux/ubuntu/gpg

- name: Add Docker APT repository
  apt_repository:
    repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable

- name: Install list of packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
  with_items:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - docker-ce
  - python-pip
  - openjdk-8*

- name: installer docker-py
  command: pip install docker-py
  become: true

- name: donner le droit sudo a l'utilisateurs stage pour executer docker
  command: usermod -aG docker stage
  become: true

- name: Telecharger une image Ubuntu/maven/jdk pour docker
  docker_image:
    name: goyalzz/ubuntu-java-8-maven-docker-image

- name: Telecharger une image Ubuntu/ansible pour docker
  docker_image:
    name: geerlingguy/docker-ubuntu1604-ansible

- name: Creer conteneur docker-ci
  docker_container:
    name: docker-ci
    image: goyalzz/ubuntu-java-8-maven-docker-image
    state: started
    volumes:
      - /data-docker-ci

- name: Creer conteneur docker-cd
  docker_container:
    name: docker-cd
    image: geerlingguy/docker-ubuntu1604-ansible
    state: started
    volumes:
      - /data-docker-cd