---
- name: Determine Docker version
  command: bash -c "docker version | grep Version | awk '{print $2}'"
  ignore_errors: yes
  changed_when: false
  register: cmd_docker_version

- name: Set fact if old Docker installation shall be removed
  set_fact:
    remove_old_docker: "{{ docker_remove_pre_ce | bool }} == true and {{ cmd_docker_version.stdout_lines[0] | search('-ce') }} == false"
  when: cmd_docker_version.stdout_lines is defined and cmd_docker_version.stdout_lines[0] is defined

- name: Check if Docker is running
  command: systemctl status docker
  ignore_errors: yes
  changed_when: false
  register: service_docker_status
  when: remove_old_docker | default(false) | bool == true
  become: true

- name: Stop Docker service
  service:
    name: docker
    state: stopped
  when: "service_docker_status.rc | default(1) == 0"

- name: Remove old Docker installation before Docker CE
  package:
    name: "{{ item }}"
    state: absent
  become: true
  when: remove_old_docker|default(false) | bool == true
  with_items:
    - "{{ docker_old_packages[_docker_os_dist] }}"
